apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5
        name: guestbook-ui
        ports:
        - containerPort: 80
